language: ruby
cache:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:environment:set RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: P8LO8ZsF/RRYIh7apQmdKc4JFUN9n9ZcN+TonKiqd4xBPX2o4zQDu+LuJii1VP7E5sH94JNbMNr11DzzTegmBl5gNpOQxn/lwinBWfmxzuiIu2Ua9ujilBGe3tudNRoIihOoBrVPKxbqlEOmvlyIoGk8IYsKSqmGk8sPdZKca5FMZCeBA5G9Kz2ZIqgRn+n7jPxyX9Xa1Hec+tmoKWR0G2FZ5ylHRcPMJy/Khll9b7EEDYMdGeCl2BIXb+g4c0ddAMVP3PJhRNPvd/pHLpw1SCoxE2V5WQovFac9mCqEa/q4UBgzGd0/Djzh6pcvCA/1uJCzc7KVEMsdtmqFA95LblrLWqVK8wjD1BNrreDqO5A0tA740a7ECwBNef/AJENn8+BrTUPPzWfhRM8WdxJI/0rFdc2sHZkW97NMJf+SHBj2Qmkwud1vQZP1JBZFKnG8hfs2CEaKrQs11dSgYyfdqB1L7viAKLPER2Bn3jN1Lnf2UpTi4BK9w8bF0J3KTl/NGQRTztf2bc+QVhz00L0TKC07SSiKJE1885M1BwCzC6K6WxQG8SGnj2ZScx3uf1wI9gC3DMayGsN0JeUnncfkL72sd3UStzLcdCK9rTWbLLzqnJB6NkTLf3yoXYbouzjQVm5mSNwcW+evSBVR1DtXySBmHF7DlcY1dzcnBXElDqU=
  app: gentle-cliffs-05214
  on:
    repo: ianmcnicholas/acebook-team.1
    branch: master
  skip_cleanup: 'true'
  run:
  - rake db:migrate
  - rake cleanup
