language: ruby
cache:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:environment:set RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: gT00ZMiyUHCzt0EmuAm1Mac3ipqzqtIIimNX9GzWVil2DywxQdZDJ2BWiDSxeZPLuhgnr9JAXMxJNvCfOXHnBxWdqdwGkSEoWpJYh2EqBOZAPTxvzCG6iaiCTgc+RTs/fk7pT/Z2Ll2XnEGGgLhV1rTQdpTxoOiEfnisOrQBOsUHaf5rxGRB6ZwwAQuBltpoREi+hGaGxknWLuQ+zDTDCM+imWSUP2znsHUnGxgfUk+ZEqG1xs9kwaIr8/fvfnwBY3CfBKEmHJ5KpVXyuUMTqHdEU3T0XhY9UmRhI+nOXm7GQhadcdX3YfrThK1qQjd4E5oHH3evAjCCWViJVaQG0iGdZ0JJ6Jj2B3VLNIGEG59gA00SCWCmkSHTpths94fUeIepQLA0dRdPSdfo1J5lora66p96wMPLKjBwegNAIsoFeuGP81/XfsoWiesgzTiEGippPDwnEMhSXkQiszcPnVOoA8EvX5w5YIPkksw5i2GGzs8+I2C7Pv1fZZnkYKlsxuG5JzBypYfXFaJNoBEvUmyah9094A2Yyz4Golo29oI0+WLRmFe/ZZLvM54nCqHADiwgpggH8ExzfSCiqjbc34Ager7+9CBWsHx9EMzqPeVcKgdqGO9IuozZul5XM9928fWbjdPe3+UCFYsKLPh38RKYVB4HeYaY83OpPIAwL6I=
  app: gentle-cliffs-05214
  on:
    repo: ianmcnicholas/acebook-team.1
    branch: master
  skip_cleanup: 'true'
  run:
  - rake db:migrate
  - rake cleanup
