language: ruby
cache:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:environment:set RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: rT5sQSRt25SDblxUD2sgnNF4btE+Htmj2HQg5/+Nfe1ewQbG8w4U5qm9K5veKriD6l5AXWyBzmiqtu7S3CwKP3hJxKPCRLlpfr7xKhkgNb0KFjKOd99/l7SdyA5cW000xL8p62xHKS0tMRuIlcxqy19Pb3FIV5nkwUsl4HLYAMa+yFI3lQqbZcLAJE9iD/4jLQLw8evxVp0X6eUoYkMPVEGKVn4xY1wkN8vR3T0/0ojYhzYWILQ/SgRtyNuk4K8dZiIjia/ej0ED99lk0jSJKfoWP7xo4MqpNJZbuyrsfISyZS350/aon1F1oipaFFrh2obeK09+nIiXY6t++bC+2AVUTxt3p0KWohv2UQ6jLKCqNaJ1c8EiNL6jySJIOLVp9PYpxk3MpzbPG1w0mw2iYCLbhcPwn0qbZX7mN78JWqKOgW8Y0PWIX/9yFuI5bmKGdLri5ciyjpEo8XqW6gB8XCSrsQ3ng816afspmZKUTgR4wygzui9IEyRFk+MkbSuk7MWn2VS4Va2Q5FHKBWCQuJhG2KeeiudZppcqQKJXoF9QD4xEOZI0DbPsU8TU3IlkpNiZNvKp6l/ksWG6yE0uPZa4W41xu6QyOrJRDX1KtYFz3oe2PrLdOle6C4jN4WvZo4QIxk2bb5vshkNQvX8rZHiM1P8OPOd73qyDbnbZvQA=
  app: gentle-cliffs-05214
  on:
    repo: ianmcnicholas/acebook-team.1
    branch: master
  skip_cleanup: 'true'
  run:
  - rake db:migrate
  - rake cleanup
